version: '3.8'

services:
  voiceenhancer:
    build: .
    container_name: voiceenhancer
    ports:
      - "8000:8000"  # For health check
    environment:
      - TOKEN=${TOKEN}
      - WHITELIST=${WHITELIST}
    volumes:
      - .:/app
