version: '3.8'

services:
  voiceenhancer:
    build: .
    container_name: voiceenhancer
    ports:
      - "${PORT}:5000"
    environment:
      - TOKEN=${TOKEN}
      - WHITELIST=${WHITELIST}
    volumes:
      - .:/app